name: DevOps Cloud Engineer Lab

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
    id-token: write
    contents: read

jobs:
    devops-cloub-engineer-lab-build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Azure login
              uses: azure/login@v1
              with:
                  client-id: ${{ secrets.AZURE_CLIENT_ID }}
                  tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                  subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
                  
            - name: Create Resource Group
              id: rg
              uses: azure/arm-deploy@v1
              with:
                scope: subscription
                region: westeurope
                deploymentName: rg-${{ github.run_number }}
                template: ./modules/resourceGroup/main.bicep

            - name: Deploy Vnet
              id: vnet
              uses: azure/arm-deploy@v1
              with:
                scope: resourcegroup
                resourceGroupName: ${{ steps.rg.outputs.resourceGroupName }}
                region: westeurope
                deploymentName: vnet-${{ github.run_number }}
                template: ./modules/networking/main.bicep

            - name: Deploy AKS Cluster
              id: aks
              uses: azure/arm-deploy@v1
              with:
                scope: resourcegroup
                resourceGroupName: ${{ steps.rg.outputs.resourceGroupName }}
                region: westeurope
                deploymentName: aks-${{ github.run_number }}
                template: ./modules/aks/main.bicep
                parameters: subnetId=${{ steps.vnet.outputs.aksSubnetId }}

            - name: Get AKS credentials
              uses: azure/aks-set-context@v3
              with:
                resource-group: ${{ steps.rg.outputs.resourceGroupName }}
                cluster-name: ${{ steps.aks.outputs.clusterName }}

            - name: Install NGINX Ingress Controller
              run: |
                helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
                helm repo update
                helm upgrade --install ingress-nginx ingress-nginx/ingress-nginx \
                  --namespace ingress-nginx \
                  --create-namespace  

            - name: Deploy Hello World app
              run: |
                kubectl apply -f app/helloWorld.yaml
                kubectl rollout status deployment/hello-world

            - name: Deploy Ingress
              run: |
                kubectl apply -f app/helloIngress.yaml
